spring:
#  profiles.active: local
  datasource:
    url:  jdbc:postgresql://mddb.postgres.database.azure.com:5432/be
    username: md@mddb
    password: Parola123
#psql postgresql://md%40mddb@mddb.postgres.database.azure.com:5432/be

    platform: postgres
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:26257/be?sslmode=disable
#    username: root
#    password:
    hikari:
      auto-commit: false
      connectionTimeout: 30000
      maxLifetime: 300000
      maximumPoolSize: 30
    flyway:
      enabled: true
      locations: classpath:db/migration
      group: true
    jpa:
      open-in-view: false
#      show-sql: false
      show-sql: true
      generate-ddl: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
          connection:
            provider_disables_autocommit: true
          temp:
            use_jdbc_metadata_defaults: false
      hibernate:
        ddl-auto: update

logging:
  level:
#    root: WARN
#    Exposed: WARN
#    org.springframework: WARN
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: ["health", "info", "prometheus"]
  endpoint:
    prometheus:
      enabled: true
  info:
    git:
      mode: full

#Constants
azureBlobStorage:
  ACCOUNT_NAME: alicerascol
  ACCOUNT_KEY: zF7wjS+ci2XaWqNDyd3xfl5LJdky1xK2TLw7fPHvBP4K8Igzr+Dvs3aFJ4FEiA4AhN6IemwcxBVdPTT3ckFGUw==
emailService:
  PASSWORD: Email_disertatie123
  EMAIL: email123disertatie@gmail.com

hardcodedStudentEmail:
  PASSWORD: StudentTestDisertatie123
  EMAIL: student.test.disertatie@gmail.com

# DownstreamService
studentApp:
  url: http://md-wiremock.westeurope.azurecontainer.io:8080/updateStatus

# temporary path to save documents
localPath: "/home/"